// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJXec2FNaeZ6QTmsZ5PVD4nQJ8YFxI38Q',
    appId: '1:531422733811:web:4d0de1132a6bef09949e86',
    messagingSenderId: '531422733811',
    projectId: 'task-manager-app-929cc',
    authDomain: 'task-manager-app-929cc.firebaseapp.com',
    storageBucket: 'task-manager-app-929cc.firebasestorage.app',
    measurementId: 'G-97B1F6DP1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXQLqEdbkcSeEbwMrtKbh5ei9I3tagR8',
    appId: '1:531422733811:android:66f6dee76d9669a9949e86',
    messagingSenderId: '531422733811',
    projectId: 'task-manager-app-929cc',
    storageBucket: 'task-manager-app-929cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1cISfVv1yV0ZrO-UArOvZctui7QbXue0',
    appId: '1:531422733811:ios:7c79b9c0998b4cb1949e86',
    messagingSenderId: '531422733811',
    projectId: 'task-manager-app-929cc',
    storageBucket: 'task-manager-app-929cc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1cISfVv1yV0ZrO-UArOvZctui7QbXue0',
    appId: '1:531422733811:ios:7c79b9c0998b4cb1949e86',
    messagingSenderId: '531422733811',
    projectId: 'task-manager-app-929cc',
    storageBucket: 'task-manager-app-929cc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJXec2FNaeZ6QTmsZ5PVD4nQJ8YFxI38Q',
    appId: '1:531422733811:web:8c3328c51fb44a1b949e86',
    messagingSenderId: '531422733811',
    projectId: 'task-manager-app-929cc',
    authDomain: 'task-manager-app-929cc.firebaseapp.com',
    storageBucket: 'task-manager-app-929cc.firebasestorage.app',
    measurementId: 'G-SKV4Y2SD07',
  );
}
